export const SOCKET_EVENTS = {
    TOKEN_CREATED: 'TOKEN_CREATED',
    TOKEN_CALLED: 'TOKEN_CALLED',
    TOKEN_COMPLETED: 'TOKEN_COMPLETED',
    TOKEN_CANCELLED: 'TOKEN_CANCELLED',
    QUEUE_UPDATED: 'QUEUE_UPDATED',
    WAIT_TIME_UPDATED: 'WAIT_TIME_UPDATED',
} as const;
